"""add profileId filed to employee table

Revision ID: 4dd8b023c477
Revises: 92059aeaa4fd
Create Date: 2022-01-07 17:58:29.531139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4dd8b023c477'
down_revision = '92059aeaa4fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('profile_id', sa.String(length=100), nullable=True))
    op.alter_column('employee', 'managed_by_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    # op.drop_constraint('employee_company_id_fkey', 'employee', type_='foreignkey')
    # op.drop_column('employee', 'company_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('company_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('employee_company_id_fkey', 'employee', 'company', ['company_id'], ['id'])
    op.alter_column('employee', 'managed_by_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.drop_column('employee', 'profile_id')
    # ### end Alembic commands ###
