"""Initial migration.

Revision ID: 4e41b0e051f2
Revises: 327ce73a778f
Create Date: 2021-11-14 20:18:04.638639

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4e41b0e051f2'
down_revision = '327ce73a778f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employee_company_id_fkey', 'employee', type_='foreignkey')
    op.drop_column('employee', 'company_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('company_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('employee_company_id_fkey', 'employee', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###
