"""Add unique constraint to company table

Revision ID: 748061ea1355
Revises: a2b9208878a9
Create Date: 2022-01-08 14:18:40.740688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '748061ea1355'
down_revision = 'a2b9208878a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'company', ['name'])
    op.drop_column('employee', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'company', type_='unique')
    # ### end Alembic commands ###
