"""Mark employee managed_by_id as nullable

Revision ID: 92059aeaa4fd
Revises: 4e41b0e051f2
Create Date: 2021-11-14 20:26:30.620803

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '92059aeaa4fd'
down_revision = '4e41b0e051f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'managed_by_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'managed_by_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###
