"""remove password from employee table

Revision ID: a2b9208878a9
Revises: 4dd8b023c477
Create Date: 2022-01-07 18:02:21.876524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b9208878a9'
down_revision = '4dd8b023c477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
